builds:
- env:
  - CGO_ENABLED=1
  main: ./cmd/kafqa/main.go
  id: kafqa
archives:
- replacements:
    linux: Linux
    amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
