language: go

go: 1.12.5

stages:
  - test
  - build
  - deploy

before_install:
  - git clone https://github.com/edenhill/librdkafka.git
  - cd librdkafka
  - ./configure --prefix /usr
  - make
  - sudo make install
  - go get -v github.com/golangci/golangci-lint/cmd/golangci-lint

before_script:
  - cd $KAFQA_DIR
env:
  PRODUCER_KAFKA_BROKERS="localhost:9092"
  CONSUMER_KAFKA_BROKERS="localhost:9092"
  GO111MODULE=on
  KAFQA_DIR=$(pwd)

jobs:
  include:
    - stage: test
      name: "Unit tests"
      script: pwd && ls ./agent/testdata/ && ls ./agent && make test
    - script: make testcodecov
      name: "Unit tests code coverage"
    - script: make check-quality
      name: "Check code quality"
    - script: make golangci
      name: "Run Golangci"
    - stage: build
      script: make clean build
    - stage: deploy
      if: tag is PRESENT
      script:
        - curl -sL https://git.io/goreleaser | bash -s -- --debug

after_success:
  - bash <(curl -s https://codecov.io/bash)
