// Code generated by protoc-gen-go. DO NOT EDIT.
// source: valid_multiple_message.proto

package com_esb_userLocation

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserDetailsLogMessage struct {
	FirstName            string               `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	EventTimestamp       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserDetailsLogMessage) Reset()         { *m = UserDetailsLogMessage{} }
func (m *UserDetailsLogMessage) String() string { return proto.CompactTextString(m) }
func (*UserDetailsLogMessage) ProtoMessage()    {}
func (*UserDetailsLogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_valid_multiple_message_e042cd843f9b4199, []int{0}
}
func (m *UserDetailsLogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailsLogMessage.Unmarshal(m, b)
}
func (m *UserDetailsLogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailsLogMessage.Marshal(b, m, deterministic)
}
func (dst *UserDetailsLogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailsLogMessage.Merge(dst, src)
}
func (m *UserDetailsLogMessage) XXX_Size() int {
	return xxx_messageInfo_UserDetailsLogMessage.Size(m)
}
func (m *UserDetailsLogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailsLogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailsLogMessage proto.InternalMessageInfo

func (m *UserDetailsLogMessage) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserDetailsLogMessage) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserDetailsLogMessage) GetEventTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.EventTimestamp
	}
	return nil
}

type UserLocationLogMessage struct {
	EventTimestamp       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserLocationLogMessage) Reset()         { *m = UserLocationLogMessage{} }
func (m *UserLocationLogMessage) String() string { return proto.CompactTextString(m) }
func (*UserLocationLogMessage) ProtoMessage()    {}
func (*UserLocationLogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_valid_multiple_message_e042cd843f9b4199, []int{1}
}
func (m *UserLocationLogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLocationLogMessage.Unmarshal(m, b)
}
func (m *UserLocationLogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLocationLogMessage.Marshal(b, m, deterministic)
}
func (dst *UserLocationLogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLocationLogMessage.Merge(dst, src)
}
func (m *UserLocationLogMessage) XXX_Size() int {
	return xxx_messageInfo_UserLocationLogMessage.Size(m)
}
func (m *UserLocationLogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLocationLogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserLocationLogMessage proto.InternalMessageInfo

func (m *UserLocationLogMessage) GetEventTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.EventTimestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*UserDetailsLogMessage)(nil), "com.esb.userLocation.userDetailsLogMessage")
	proto.RegisterType((*UserLocationLogMessage)(nil), "com.esb.userLocation.userLocationLogMessage")
}

func init() {
	proto.RegisterFile("valid_multiple_message.proto", fileDescriptor_valid_multiple_message_e042cd843f9b4199)
}

var fileDescriptor_valid_multiple_message_e042cd843f9b4199 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x8f, 0x4d, 0x4a, 0xc5, 0x30,
	0x10, 0xc7, 0x89, 0x82, 0xd8, 0x08, 0x0a, 0x45, 0xe5, 0xf1, 0x54, 0x7c, 0x74, 0xd5, 0x55, 0x0a,
	0x7a, 0x04, 0x5d, 0x56, 0x17, 0xc5, 0xad, 0x84, 0x69, 0x9d, 0x86, 0x40, 0xd2, 0x29, 0xcd, 0xb4,
	0x67, 0xf1, 0xb8, 0xd2, 0x94, 0x96, 0x1e, 0xc0, 0x65, 0xfe, 0x5f, 0xf9, 0x8d, 0x7c, 0x9c, 0xc0,
	0xd9, 0x1f, 0xed, 0x47, 0xc7, 0xb6, 0x77, 0xa8, 0x3d, 0x86, 0x00, 0x06, 0x55, 0x3f, 0x10, 0x53,
	0x7a, 0xdb, 0x90, 0x57, 0x18, 0x6a, 0x35, 0x06, 0x1c, 0x4a, 0x6a, 0x80, 0x2d, 0x75, 0xc7, 0x67,
	0x43, 0x64, 0x1c, 0x16, 0x31, 0x53, 0x8f, 0x6d, 0xc1, 0xd6, 0x63, 0x60, 0xf0, 0xfd, 0x52, 0xcb,
	0x7e, 0x85, 0xbc, 0x9b, 0x1b, 0xef, 0xc8, 0x60, 0x5d, 0x28, 0xc9, 0x7c, 0x2c, 0xb3, 0xe9, 0x93,
	0x94, 0xad, 0x1d, 0x02, 0xeb, 0x0e, 0x3c, 0x1e, 0xc4, 0x49, 0xe4, 0x49, 0x95, 0x44, 0xe5, 0x13,
	0x3c, 0xa6, 0x0f, 0x32, 0x71, 0xb0, 0xba, 0x67, 0xd1, 0xbd, 0x9c, 0x85, 0x68, 0xbe, 0xc9, 0x1b,
	0x9c, 0xb0, 0x63, 0xbd, 0x7d, 0x77, 0x38, 0x3f, 0x89, 0xfc, 0xea, 0xe5, 0xa8, 0x16, 0x20, 0xb5,
	0x02, 0xa9, 0xaf, 0x35, 0x51, 0x5d, 0xc7, 0xca, 0xf6, 0xce, 0xbe, 0xe5, 0xfd, 0xfe, 0x96, 0x1d,
	0xda, 0x7f, 0xcc, 0xd7, 0x17, 0x31, 0xf3, 0xfa, 0x17, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x2b, 0x66,
	0x7d, 0x57, 0x01, 0x00, 0x00,
}
