{
 "title": "Kafqa",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Messages sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(messages_received[1m]))",
     "legendFormat": "messages_received"
    },
    { "expr": "sum(rate(messages_sent[1m]))", "legendFormat": "messages_sent" }
   ]
  },
  {
   "title": "Messages Received / 30s ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(messages_received[30s]))",
     "legendFormat": "messages_sent"
    }
   ]
  },
  {
   "title": "Latency Receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "latency_ms_receive" }
   ]
  }
 ]
}