name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - kafqa*
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: install librdkafka
        run: |
          git clone https://github.com/edenhill/librdkafka.git
          pushd librdkafka && ./configure --prefix /usr
          sudo make
          sudo make install
          popd
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

